"""no more payment method

Revision ID: 2af8d89e6606
Revises: 21eda9bdf6ef
Create Date: 2025-07-24 00:48:40.107300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2af8d89e6606'
down_revision = '21eda9bdf6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
