"""Added Address columns to thr client table

Revision ID: c816d4ca7a78
Revises: 2af8d89e6606
Create Date: 2025-07-27 20:50:38.509273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c816d4ca7a78'
down_revision = '2af8d89e6606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('post_code', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('post_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
